#spring:
#  jackson:
#    deserialization:
#      fail-on-unknown-properties: true
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#      database-platform: org.hibernate.dialect.MySQL8Dialect
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/student
#    username: testuser
#    password: test1990%%
#    driver-class-name: com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql: true

spring:
  jpa:
    hibernate:
      ddl-auto: create
      database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driver-class-name: org.h2.Driver